### ISSUE TITLE
[Docs]: make available Postman or Insomnia collection

### ISSUE THREAD

**Issue by fabioalmeida100** [Mayank0255/Stackoverflow-Clone-Backend#16]
My proposal: it'll be good have a collection with all endpoints and payload pre setup to new developers understand more fast all possibilities of request to back-end.

I have all endpoint setup in Postman collection, so if it's a good idea I can open a PR to make available it in Postman.

**Comment by Mayank0255** [comment]
@fabioalmeida100 Yes that seems a good idea.
