### ISSUE TITLE
[BUG]: sql files are incorrect

### ISSUE THREAD

**Issue by AiPacino** [Mayank0255/Stackoverflow-Clone-Backend#31]
sql file is not same modle design

sql:
CREATE TABLE users(
  id VARCHAR(255) PRIMARY KEY,
  username VARCHAR(255) UNIQUE NULL,
  password VARCHAR(100),
  views INT DEFAULT 0,
  gravatar VARCHAR(255) UNIQUE NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
);

model:
  id: {
    type: DataTypes.UUID,
    allowNull: false,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4,
  },

**Comment by Mayank0255** [comment]
Hi @AiPacino,

Yes, I know about this, the thing is that I have recently migrated to sequelize, so the sql files are redundant/outdated now.

I haven't updated the docs yet as I am currently working on some archtectural changes.

If you want to setup the project, then for the backend do not follow the documentation provided completely, and,
1. First setup your `.env` file as stated in the docs.
2. Then just create the database with whatever name you want to give it and update your `.env` accordingly
3. You don't need to create the tables just the database
4. After this is done just run `npm start` and the server will automatically create the required tables with the updated schemas.

After that, just have fun with the product 🎉

**Comment by Mayank0255** [comment]
@AiPacino Checkout the updated SQL files, those are the correct ones
