### ISSUE TITLE
[Backend]: Separation of Queries of existing Models

### ISSUE THREAD

**Issue by Mayank0255** [Mayank0255/Stackoverflow-Clone-Backend#4]
**Context**

This is the first task of Mayank0255/Stackoverflow-Clone-Backend#2, in which the existing queries will be separated first from the models

**Comment by Bootspace** [comment]
Hey @Mayank0255 can you explain in more detail what this issue is and what exactly is to be done here.

**Comment by Mayank0255** [comment]
@Bootspace 

Actually someone is already working on this issue, and this is a part of #2.

But you are more than welcomed to work on any other issue or create one yourself
