### ISSUE TITLE
[Backend]: Add Docker support for development and production

### ISSUE THREAD

**Issue by navarrojava** [Mayank0255/Stackoverflow-Clone-Backend#5]
To Helps with initial setup and ensures the integrity of the app

Add docker support for the development and production environment. Creating a Dockerfile and docker-compose files, Adding all the necessary environment like Mysql together with compose.

**Comment by irvv17** [comment]
Hi @Mayank0255 Can you assign this to me I want to work on it and also add the label

**Comment by Mayank0255** [comment]
@irvv17, actually this one is on hold for now, as the backend code needs to be improved via sequelize and all first.

I am willing to anyother proposals as well, Front or back

**Comment by fabioalmeida100** [comment]
@Mayank0255 assign to me. I have the .Dockerfile ready for close this issue in back-end.

**Comment by Mayank0255** [comment]
@fabioalmeida100 great👍

**Comment by fabioalmeida100** [comment]
Open PR: https://github.com/Mayank0255/Stackoverflow-Clone-Backend/pull/11
